### ISSUE TITLE
[FR] Time Ago Functions

### ISSUE THREAD

**Issue by samstevens** [TopShelfCraft/Wordsmith#1]
Hi guys,

This is a great tool and should be the go-to resource for all twig helpers.

I think adding a "time ago" function would be handy.
https://github.com/MDXDave/time-ago

Having parameters for displaying "ago" or "in" (eg: 2 days ago, in 7 days) would be nice.

Moment.js does a great job of this with their implementation 
https://momentjs.com/docs/#/displaying/fromnow/

A PHP port is available here: https://github.com/fightbulc/moment.php

Keep up the good work!

**Comment by michaelrog** [comment]
The native [`duration` filter](https://craftcms.com/docs/3.x/dev/filters.html#duration) probably meets this need well enough for now...?
