### ISSUE TITLE
Words with non ascii characters incorrectly handled by apTitleize filter

### ISSUE THREAD

**Issue by piotrpog** [TopShelfCraft/Wordsmith#14]
In my case, word `Przykładowa` was changed to `PrzykłAdowa` - first letter after non ascii character was capitalized.

**Comment by michaelrog** [comment]
I still want to enact a real fix for this issue, but in the meantime (as of 4.1.0), you can configure `protectedTitleWords` as a stopgap to handle known exceptions like this.

**Comment by michaelrog** [comment]
Actually, I worked out a solutions to this, and also improved title handling for several other corner cases, too. No hacks/stopgaps necessary. 🎉
