### ISSUE TITLE
Typography issues in PHP 7.3

### ISSUE THREAD

**Issue by michaelrog** [TopShelfCraft/Wordsmith#17]
There appear to be some issues with the PHP-Typography library and PHP 7.3, which our users might run into eventually:

https://github.com/mundschenk-at/php-typography/issues/109

**Comment by michaelrog** [comment]
c.f. https://github.com/craftcms/cms/issues/4239

**Comment by angrybrad** [comment]
Should be resoved in https://github.com/craftcms/cms/commit/8bf818a2e61a3468ab4630e45a9ad9ad42503975, which will be in the next release.

**Comment by jalendport** [comment]
Thank you @angrybrad!
