### ISSUE TITLE
Stringy Naming Collision

### ISSUE THREAD

**Issue by jmauzyk** [TopShelfCraft/Wordsmith#25]
Just installed Craft 3.3 and was starting to test it when I ran into a naming collision issue with Stringy. Craft 3.3 switches from `danielstjules/Stringy` to `voku/Stringy`. This wouldn't be an issue except that Craft 3.3 now uses the `snakeize()` method (unique to voku) for the `|snake` twig filter. Because composer defaults to the old `danielstjules/Stringy` when generating autoload files, I now get a call to undefined method error when using the snake filter. Can you switch from the danielstjules version to the voku version to avoid this collision?

**Comment by lukeholder** [comment]
Also getting this. collision with Crafts built in Stringy/Stringy

**Comment by vaughn-taylor** [comment]
I have an issue as well as reported [here](https://github.com/craftcms/cms/issues/4753). Apparently `danielstjules/Stringy` needs to be updated to `voku/Stringy` in `topshelfcraft/wordsmith`.
