### ISSUE TITLE
[FR] Allow erusev/parsedown-extra 0.8

### ISSUE THREAD

**Issue by mattstein** [TopShelfCraft/Wordsmith#29]
It's [finally stable](https://github.com/erusev/parsedown-extra/releases)! [Others have required it recently](https://github.com/selvinortiz/craft-plugin-doxter/commit/f1e874e3918e7c1d7a5a66f322be7b9d5f1178fd) and this could hopefully solve [an ancient rift](https://github.com/TopShelfCraft/Wordsmith/issues/22).

**Comment by michaelrog** [comment]
Give me your hands if we be friends,
 And @mattstein shall restore amends.

— Shakespeare, Act III, Scene 92d0e41.

**Comment by jalendport** [comment]
Haha best comment on GitHub I've seen in a while 👏😂
