### ISSUE TITLE
Vimeo Filter

### ISSUE THREAD

**Issue by kaspar-allenbach** [TopShelfCraft/Wordsmith#30]
Would you mind adding vimeo support?

`https://player.vimeo.com/video/22439234`
`https://vimeo.com/22439234`

`{{ handle |vimeoId }}`

> 22439234

This would be awesome

**Comment by michaelrog** [comment]
Yes, I'll put it on the to-do list.

If you beat me to it, please PR to the `3.x.dev` branch!  🎬

**Comment by michaelrog** [comment]
Added in 8237946, released in `4.2.0`. ✅
