### ISSUE TITLE
Widont Not Working

### ISSUE THREAD

**Issue by kerns** [TopShelfCraft/Wordsmith#32]
Or at least this is how it feels. What might I be doing wrong? Neither of these is working.

```
{% filter widont %}{{ entryTitle }}{% endfilter %}
{{ entryTitle|widont }}
```

**Comment by michaelrog** [comment]
To troubleshoot, it'd be helpful to know the actual text of `entryTitle` in your example. — Could you try running a raw string (rather than a variable) through the filter, and let us know the output?

(Also, check to see if your case is similar to #5, where `widont` ignores sufficiently long words...?)

**Comment by kerns** [comment]
Sure. the headline in this case was `Rare and Fully Documented Giulietta Sprint`

`{% filter widont %}Voluptatem numquam nesciunt voluptates ipsasdsdsdsd explicabo!{% endfilter %}`is not responding either. 🤔

**Comment by kerns** [comment]
Any other ideas or things I might test to help debug this?

**Comment by michaelrog** [comment]
As I suspected, this is a repeat of #5. 

By default, `widont` only takes effect if the widowed line would be shorter than 5 characters.

You can tweak this by adding more aggressive settings in your `wordsmith.php` config file:
```php
return [
    'typographySettings' => [
        'set_max_dewidow_length' => 25,
        'set_max_dewidow_pull' => 25,
    ]
];
```

**Comment by michaelrog** [comment]
Since this is a common issue, I'm going to raise the threshold to 10 characters. Update to Wordsmith 3.3 to get that adjustment.
