### ISSUE TITLE
Reference to deprecated vue-asset

### ISSUE THREAD

**Issue by alekslinde** [TopShelfCraft/Wordsmith#35]
Trying to upgrade to 3.3.0 and it gives me the following error:

>  Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
> Package "danielstjules/stringy" listed for update is not installed. Ignoring.
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Conclusion: remove voku/stringy 5.1.1
> - Conclusion: remove craftcms/cms 3.4.27
> - topshelfcraft/wordsmith 3.3.0 requires craftcms/cms ^3.3 -> satisfiable by craftcms/cms[3.4.27].
> - Conclusion: don't install craftcms/cms 3.4.27
> - Conclusion: don't install voku/stringy 5.1.1
> - Installation request for topshelfcraft/wordsmith 3.3.0 -> satisfiable by topshelfcraft/wordsmith[3.3.0].
> - Conclusion: don't install voku/stringy 6.3.1
> - topshelfcraft/wordsmith 3.3.0 requires voku/stringy ^6.0 -> satisfiable by voku/stringy[6.3.1, 6.3.0, 6.2.2].
> - Can only install one of: voku/stringy[6.3.0, 5.1.1].
> - Can only install one of: voku/stringy[6.2.2, 5.1.1].
> - craftcms/cms 3.4.27 requires voku/stringy ~5.1.0 -> satisfiable by voku/stringy[5.1.1, 5.1.0].
> - Conclusion: don't install voku/stringy 5.1.0|install voku/stringy 6.3.1
> 
> Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

By the look on the first error it seems that Wordsmith requires craftcms/vue-asset which is now deprecated - https://github.com/craftcms/vue-asset .

**Comment by michaelrog** [comment]
🤔  Wordsmith does not require or reference `vue-asset`.

**Comment by michaelrog** [comment]
The issue is that Craft versions earlier than 3.5 aren't compatible with Stringy v6. Therefore, 3.3.0 is retagged to only be compatible with Craft 3.5+.

**Comment by alekslinde** [comment]
CraftCMS 3.5 is in beta - probably not going to use just yet. It will be great having the update not being available to any other CraftCMS version before 3.5.
