### ISSUE TITLE
Problem upgrading to Craft 3.5 with Wordsmith 3.2 installed

### ISSUE THREAD

**Issue by idawgik** [TopShelfCraft/Wordsmith#37]
_Update: Craft 3.5 requires Wordsmith 3.3._

#### 📌  ... The [solution](https://github.com/TopShelfCraft/Wordsmith/issues/37#issuecomment-670040571):

1. Uninstall Wordsmith (3.2)
2. Update Craft (3.5)
3. Re-install Wordsmith (3.3)

* * * *

Hello,

I'm attempting to upgrade to Craft 3.5.0 on a site using Wordsmith.

I get the following errors during the composer updates:

```
Output:

<warning>Package "craftcms/vue-asset" listed for update is not installed. Ignoring.</warning>
<warning>Package "danielstjules/stringy" listed for update is not installed. Ignoring.</warning>
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove topshelfcraft/wordsmith 3.2.0
    - Conclusion: don't install topshelfcraft/wordsmith 3.2.0
    - Conclusion: don't install voku/stringy 5.2.0
    - Conclusion: don't install voku/stringy 6.3.1
    - Conclusion: remove voku/stringy 5.1.1|install voku/stringy 6.3.1
    - Conclusion: don't install voku/stringy 5.1.1
    - Installation request for topshelfcraft/wordsmith 3.2.0 -> satisfiable by topshelfcraft/wordsmith[3.2.0].
    - Installation request for craftcms/cms 3.5.0 -> satisfiable by craftcms/cms[3.5.0].
    - topshelfcraft/wordsmith 3.2.0 requires voku/stringy ^5.1.0 -> satisfiable by voku/stringy[5.1.1, 5.2.0, 5.1.0].
    - Can only install one of: voku/stringy[5.1.0, 6.2.2].
    - Can only install one of: voku/stringy[6.2.2, 5.1.1].
    - craftcms/cms 3.5.0 requires voku/stringy ^6.2.2 -> satisfiable by voku/stringy[6.3.1, 6.3.0, 6.2.2].
    - Conclusion: don't install voku/stringy 6.3.0
```

It looks like there's a conflict with the plugin and Craft both requiring different versions of the Stringy library.

**Comment by kerns** [comment]
Same issue. Had to completely remove the plugin and am now sifting through templates to remove all my beloved `|widont`filters. Hope this can be resolved. 👍

**Comment by moondawg69** [comment]
Same issue here as well. Hope this can be resolved as well please :)

**Comment by mariussunde** [comment]
Same!

**Comment by michaelrog** [comment]
Make sure your dependency constraint for Wordsmith allows the latest version of Wordsmith (3.3.0) to be installed.

(Wordsmith 3.3 uses a later version of Stringy in order to be compatible with Craft 3.5, so you should be able to update both in tandem. Versions of Wordsmith prior to 3.3 will not be compatible with Craft 3.5.)

**Comment by michaelrog** [comment]
(@kerns @moondawg69 @mariussunde — feel free to post your `composer.json` files if you'd like help updating your dependency constraints to be Craft 3.5-ready.)

**Comment by moondawg69** [comment]
If you could advise on the composer files please, that would be handy, thank you.


[Archive.zip](https://github.com/TopShelfCraft/Wordsmith/files/5035746/Archive.zip)

**Comment by michaelrog** [comment]
@moondawg69 — just add a `^` to your dependency constraint for Wordsmith, like this:
```
"topshelfcraft/wordsmith": "^3.2.0",
```
That'll ensure maximum interoperability with future versions of Wordsmith and Craft.

Curiously, did you install Wordsmith via the command-line Composer tool, or from the Craft Plugin Store?

**Comment by moondawg69** [comment]
Thank you @michaelrog - I changed composer.json to: "topshelfcraft/wordsmith": "^3.2.0",

Logged into the CP and ran the 3.5 update, same(ish) issue, but slightly different:

```
Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Package "danielstjules/stringy" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- topshelfcraft/wordsmith 3.2.0 requires craftcms/cms 3.3 - 3.4 -> satisfiable by craftcms/cms[3.3.0, 3.3.0.1, 3.3.1, 3.3.1.1, 3.3.1.2, 3.3.2, 3.3.3, 3.3.4, 3.3.4.1, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9, 3.3.10, 3.3.11, 3.3.12, 3.3.13, 3.3.14, 3.3.15, 3.3.16, 3.3.16.1, 3.3.16.2, 3.3.16.3, 3.3.17, 3.3.18, 3.3.18.1, 3.3.18.2, 3.3.18.3, 3.3.18.4, 3.3.19, 3.3.20, 3.3.20.1, 3.4.0-beta.1, 3.4.0-beta.2, 3.4.0-beta.3, 3.4.0-beta.4, 3.4.0-beta.5, 3.4.0-RC1, 3.4.0-RC1.1, 3.4.0-RC2, 3.4.0-RC3, 3.4.0, 3.4.0.1, 3.4.0.2, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.4.1, 3.4.5, 3.4.6, 3.4.6.1, 3.4.7, 3.4.7.1, 3.4.8, 3.4.9, 3.4.10, 3.4.10.1, 3.4.11, 3.4.12, 3.4.13, 3.4.14, 3.4.15, 3.4.16, 3.4.17, 3.4.17.1, 3.4.18, 3.4.19, 3.4.19.1, 3.4.20, 3.4.21, 3.4.22, 3.4.22.1, 3.4.23, 3.4.24, 3.4.25, 3.4.26, 3.4.27, 3.4.28, 3.4.28.1, 3.4.29, 3.4.29.1, 3.4.30] but these conflict with your requirements or minimum-stability.
- Conclusion: remove topshelfcraft/wordsmith 3.2.0
- Conclusion: don't install voku/stringy 5.2.0
- Conclusion: don't install voku/stringy 6.3.1
- Conclusion: remove voku/stringy 5.1.1
- Installation request for topshelfcraft/wordsmith (locked at 3.2.0, required as ^3.2.0) -> satisfiable by topshelfcraft/wordsmith[3.2.0].
- Installation request for craftcms/cms 3.5.1 -> satisfiable by craftcms/cms[3.5.1].
- topshelfcraft/wordsmith 3.2.0 requires voku/stringy ^5.1.0 -> satisfiable by voku/stringy[5.1.1, 5.2.0, 5.1.0].
- Can only install one of: voku/stringy[5.1.0, 6.2.2].
- Can only install one of: voku/stringy[5.1.1, 6.2.2].
- Can only install one of: voku/stringy[6.2.2, 5.1.1].
- craftcms/cms 3.5.1 requires voku/stringy ^6.2.2 -> satisfiable by voku/stringy[6.3.1, 6.3.0, 6.2.2].
- Conclusion: don't install voku/stringy 6.3.0
```

And yes, always via the Plugin Store, do not touch the command line or SSH.

**Comment by michaelrog** [comment]
Thanks for troubleshooting this with me, @moondawg69!

Try this:

1. Update your Composer file to reflect the most recent versions of Wordsmith _and_ Craft:
```
"craftcms/cms": "^3.5",
...
"topshelfcraft/wordsmith": "^3.3",
```

2. Run Composer's update command:
```
composer update
```

3. From the Craft control panel, update any remaining items.

**Comment by moondawg69** [comment]
Ok, I'll have to get the host to open up SSH on this particular domain to run the composer command. 

I'll let you know :)

**Comment by michaelrog** [comment]
Actually, @moondawg69 ... you _might_ be able to get away with just updating the `composer.json` and then running the update through Craft.

(The difference between now and earlier is that you're unpinning the version constraint for _both_ Craft _and_ Wordsmith. Maybe that'll make a difference in how Craft's updater resolves the update.) 🤞

**Comment by moondawg69** [comment]
I tried that route first ;)

Error was:

Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Package "danielstjules/stringy" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package topshelfcraft/wordsmith (locked at 3.2.0, required as ^3.3) is satisfiable by topshelfcraft/wordsmith[3.2.0] but these conflict with your requirements or minimum-stability.

**Comment by michaelrog** [comment]
A ha — That indicates a mismatch between your `composer.json` and `composer.lock` files. (This is expected, since you edited your `composer.json` file, and haven't (yet) run `composer update` to rebuild the lock file with the updated dependencies.

Try deleting your `composer.lock` file (keep a backup copy, of course) — And see if Craft regenerates it in the course of an update?

**Comment by moondawg69** [comment]
Getting worse lol - composer update ends up in a KILLED status, memory I guess.

So, renaming composer lock and running via the CP, gets:

Composer output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package topshelfcraft/wordsmith (installed at 3.2.0, required as ^3.3) is satisfiable by topshelfcraft/wordsmith[3.2.0] but these conflict with your requirements or minimum-stability.
Problem 2
- Can only install one of: yiisoft/yii2[2.0.35, 2.0.36].
- Can only install one of: yiisoft/yii2[2.0.36, 2.0.35].
- craftcms/cms 3.5.1 requires yiisoft/yii2 ~2.0.36.0 -> satisfiable by yiisoft/yii2[2.0.36].
- Installation request for craftcms/cms 3.5.1 -> satisfiable by craftcms/cms[3.5.1].
- Installation request for yiisoft/yii2 (installed at 2.0.35) -> satisfiable by yiisoft/yii2[2.0.35].

**Comment by michaelrog** [comment]
Blergh. So, to summarize:

Wordsmith 3.3 requires Craft 3.5, but you can't update to Craft 3.5 with Wordsmith 3.2 installed. This is fine if you're running `composer update` on the command line, because Composer is smart enough to rebuild the dependency tree and update all the packages in tandem. But, Craft's updater apparently doesn't work like that.

So, the solution for right now is dumb, but simple:

**Uninstall Wordsmith, update Craft, re-install Wordsmith.**

**Comment by michaelrog** [comment]
To summarize:

- Wordsmith 3.3 requires Craft 3.5, but you can't update to Craft 3.5 with Wordsmith 3.2 installed.

- This is fine if you're running composer update on the command line, because Composer is smart enough to rebuild the dependency tree and update all the packages in tandem.

- But, the Plugin Store updater seems to work differently, i.e. updating packages one at a time, which in this case is impossible due to the version constraints.

**The immediate solution (for Plugin Store installs) is silly, but simple:**

1. **Uninstall Wordsmith** (3.2)
2. **Update Craft** (3.5)
3. **Re-install Wordsmith** (3.3)

**Comment by moondawg69** [comment]
@michaelrog well that worked, thank you:

> Uninstall Wordsmith (3.2)
> Update Craft (3.5)
> Re-install Wordsmith (3.3)

And now onto other plugins that are being naughty too :)

**Comment by michaelrog** [comment]
Thanks @idawgik for bringing this up.

@kerns @mariussunde ☝️  — Does that work for yall, too?

(Hopefully easier than ripping out all your `|widont`s...) 😅

**Comment by mariussunde** [comment]
@michaelrog oddly enough, it does not do the trick for me. I uninstalled* every plugin and still get an error so currently in touch with Craft support. 

> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Conclusion: remove tcb13/substringy 1.0.0
> - Conclusion: don't install tcb13/substringy 1.0.0
> - Conclusion: remove danielstjules/stringy 3.1.0
> - Installation request for tcb13/substringy (locked at 1.0.0) -> satisfiable by tcb13/substringy[1.0.0].
> - Installation request for craftcms/cms 3.5.1 -> satisfiable by craftcms/cms[3.5.1].
> - Conclusion: don't install voku/stringy 6.3.1
> - craftcms/cms 3.5.1 requires voku/stringy ^6.2.2 -> satisfiable by voku/stringy[6.3.1, 6.3.0, 6.2.2].
> - don't install voku/stringy 6.3.0|don't install danielstjules/stringy 3.1.0
> - don't install voku/stringy 6.2.2|don't install danielstjules/stringy 3.1.0
> - tcb13/substringy 1.0.0 requires danielstjules/stringy ^3.1 -> satisfiable by danielstjules/stringy[3.1.0].
> - Conclusion: don't install danielstjules/stringy 3.1.0|install voku/stringy 6.3.1

**Comment by michaelrog** [comment]
@mariussunde — Sounds like there may be lingering references to `danielstjules/stringy`, `tcb13/substringy`, or Wordsmith, in your `composer.json` or `composer.lock`...? You may need to clean those out before the Plugin Store updater will let you proceed.

**Comment by kerns** [comment]
> Thanks @idawgik for bringing this up.
> 
> @kerns @mariussunde ☝️ — Does that work for yall, too?
> 
> (Hopefully easier than ripping out all your `|widont`s...) 😅

Much easier! Worked perfectly for me. Thanks!
