### ISSUE TITLE
Dependency erusev/parsedown-extra with PSR-0 issues

### ISSUE THREAD

**Issue by ostark** [TopShelfCraft/Wordsmith#43]
Not your issue, but still an issue:

https://github.com/erusev/parsedown-extra/issues/156

**Comment by michaelrog** [comment]
Grumpgrumpgrump. Thanks for calling that to my attention.

**Comment by peteeveleigh** [comment]
Looks like there was a pull request for this made in the erusev/parsedown-extra package but it's been sitting there since May 2020. Not sure what can be done from here without forking it and fixing the problem. Doesn't look like the author is interested in it any longer.

**Comment by michaelrog** [comment]
From the POV of Wordsmith, it looks like a mostly aesthetic issue... i.e. Composer is complaining about invalid namespacing for `ParsedownExtraTest`, but that class isn't used invoked by Wordsmith. So as far as I know, it's not breaking any of the plugin's functionality. Am I missing something?

**Comment by ostark** [comment]
Depends if your FS is case sensitive or not.
Previously Composer wasn't strict about casing, now with 2.0 it is.
Composer doesn't know if you will use the class later. To avoid surprises later, it makes sense to complain about it.

**Comment by peteeveleigh** [comment]
@michaelrog if you are using Composer 2 and running `composer install` on deployment then it can fail with an error and not do the autoload thing.
I will double check it though.
Maybe it won't be a problem as it will only skip that particular class

**Comment by michaelrog** [comment]
yeah, I'm using Composer 2, but I just see warnings, and it installs just fine.

**Comment by ostark** [comment]
I suggest to fork it since further development by maintainer is unlikely. Or use a different package.

**Comment by michaelrog** [comment]
For sure — Will probably ditch Parsedown Extra altogether in 4.0, and just use GFM via The League's package.

Also want to fix any _breaking_ issues in 3.x, so just trying to confirm if _this_ present issue is, in fact, "breaking" (as opposed to just annoying).

**Comment by peteeveleigh** [comment]
On reflection I don’t think it’s breaking.

**Comment by ademers** [comment]
I've just noticed this today:

```
Deprecation Notice: Class ParsedownExtraTest located in ./vendor/erusev/parsedown-extra/test/ParsedownExtraTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

Can someone please confirm that this won't bork my Production env. when I finally upgrade to Composer 2? Thanks!

**Comment by michaelrog** [comment]
@ademers — should be fine. The `ParsedownExtraTest` class isn't required for any functionality, so it's not concerning that it doesn't get loaded by Composer 2. (In the next version, I'll probably just remove the dependency, cuz nobody likes to be pestered.)
