### ISSUE TITLE
Array and string offset access syntax with curly braces is no longer supported

### ISSUE THREAD

**Issue by gixxy22** [TopShelfCraft/Wordsmith#45]
in /vendor/topshelfcraft/wordsmith/src/libs/FullNameParser.phpat line 476 

`return ((mb_strlen($word) == 1) || (mb_strlen($word) == 2 && $word{1} == "."));`

curly braces are no longer supported in PHP8

**Comment by gixxy22** [comment]
theres a few other lines where curly braces are used in that file too.

**Comment by michaelrog** [comment]
Thanks for bringing this up. Will get an 8.0-friendly update out.
