### ISSUE TITLE
[FR] Add GraphQL support for filters as directives

### ISSUE THREAD

**Issue by denisyilmaz** [TopShelfCraft/Wordsmith#46]
Would it be possible to add the filters (like `{{'Mark & Sons: "industry leaders" in... stuff.' | typogrify}}`) to GraphQL as directives?
It would be awesome to be able to parse text in graphql like this:

```gql
{
    entry {
        id
        title @titleize
        slug
        content @typogrify
    }
}
```

**Comment by michaelrog** [comment]
That's a GREAT idea! — I imagine it'd be useful for a lot of folks!

You can [define custom directives](https://craftcms.com/docs/3.x/extend/graphql.html#directives) using Craft's [`Gql::EVENT_REGISTER_GQL_DIRECTIVES`](https://docs.craftcms.com/api/v3/craft-services-gql.html#event-register-gql-directives) event.

The trick would be... How can we avoid needing to create and register dozens of PHP classes (one for each of Wordsmith's functions)?

Maybe a catch-all `@wordsmith` directive could work? Then you'd have a syntax like:

```graphql
{
    entry {
        id
        title @wordsmith(function: "titleize")
        slug
        content @wordsmith(function: "typogrify", args: [])
    }
}
```

Alternatively, for sugar, I can envision a config setting like
```php
return [
    'registerGqlDirectives' => [
        'titleize',
        'typogriphy',
    ],
]
```
...that could dynamically instantiate and register directives, allowing a shorter syntax like the one in your example.

If you pursue this, _please_ PR to the `dev` branch! This would make an awesome contribution!

**Comment by denisyilmaz** [comment]
I like the idea of having one single `@wordsmith`directive. I have created a PR with all functions which return string/boolean and don't need any arguments to work correctly or have defaults set.

![image](https://user-images.githubusercontent.com/4189607/146744618-2c717bf6-8806-4b51-b11c-19a830686fc0.png)


It might be necessary to declare different directives for the functions with arguments because this would make it easier to keep the syntax for the arguments in sync with the original functions and provide better GraphQL Schema insights.
Additionally, the return type might not be editable to something else then `string` (currently the functions which return an `int` or `boolean` are returning these as `string`, which works, but is not as intended).

**Comment by mihob** [comment]
Any news on this topic? That would really be a great feature

**Comment by michaelrog** [comment]
I've pushed an implementation of this functionality to `4.x.dev` with the intention of releasing it in `4.3.0`.

For now, I went with a single `@wordsmith` directive, which supports any function that doesn't require arguments.

(The way Craft has implemented custom GQL Directives requires the `apply()` logic to be in a static context; Unfortunately, that prohibits my idea for generating/registering directives dynamically, at least for now.)

**Comment by michaelrog** [comment]
Wordsmith `4.5.0` and `5.0.0` are out with official support for this new `@wordsmith` GQL directive. ✅
