### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by rob-c-baker** [TopShelfCraft/Wordsmith#49]
Just wondering about Craft 4 support for Wordsmith.

Looking through the current issues, these seem related (or are blockers):

#34 Update `icanboogie/inflector` to 2.0 for PHP 7.4 support  
#45 Array and string offset access syntax with curly braces is no longer supported  

Both of these explicitly or implicitly need work for PHP 8.x support.

**Comment by michaelrog** [comment]
Wordsmith 4.0.0 is out now, with Craft 4 compatibility.

#34 is resolved by pinning the Inflector package at `^2.0`.

#45 is still open; PRs welcome!

**Comment by michaelrog** [comment]
#45 is closed as of `4.0.1`. ✅ 

(Thanks @Saboteur777!)
