### ISSUE TITLE
Add `encode` parameter to `markdown` & `md` filters

### ISSUE THREAD

**Issue by j-add** [TopShelfCraft/Wordsmith#57]
Craft v4.5.13 introduces a change to `markdown` and `md` filters, giving them an `encode` parameter. CP templates have been updated to use this functionality. This results in a `Twig Syntax Error` being thrown when the unknown argument (encode) is passed to the filter. 

Error encountered on `admin/utilities/deprecation-errors` page.

--- 

>-  The `|markdown` and `|md` filters now accept an encode argument, which can be set to true to HTML-encode the content before parsing it as Markdown.
- [https://github.com/craftcms/cms/releases/tag/4.5.13](https://github.com/craftcms/cms/releases/tag/4.5.13)

[Relevant commit](https://github.com/craftcms/cms/commit/bf8a69f53fa85c385e3b8987af1ff577ca743b5a)

**Comment by DynamiteGoesBoom** [comment]
I'm running into this same issue.

**Comment by DynamiteGoesBoom** [comment]
Looks like reverting to `4.5.11.1` fixes it

**Comment by scandella** [comment]
Reverting to 4.5.12 works fine too.

**Comment by michaelrog** [comment]
Thanks for calling this in. At the very least, I'll adjust the plugin to prevent overriding those filters in the `cp` template mode.

**Comment by michaelrog** [comment]
✅ Wordsmith 4.4.0 is out with a change to avoid conflicting w/ Craft's filters in the CP.

Wordsmith's `markdown` and `md` are now deprecated, and I'll remove them in Wordsmith 5.0, since Craft now provides this functionality natively.
