### ISSUE TITLE
GraphQL Error

### ISSUE THREAD

**Issue by Lugat** [TopShelfCraft/Wordsmith#58]
We are getting the following error:
Object of class TopShelfCraft\\Wordsmith\\gql\\WordsmithDirective could not be converted to string

Could fix it by changing the following code:

TopShelfCraft\Wordsmith\Wordsmith
Line: 64
`$event->directives[] = WordsmithDirective::create();`
to
`$event->directives[] = WordsmithDirective::class;`

**Comment by michaelrog** [comment]
Thanks @Lugat for calling this to my attention. Wordsmith `4.5.0` and `5.0.0` include the change you suggested. ✅
