### ISSUE TITLE
Craft CMS 5 compatibility

### ISSUE THREAD

**Issue by vonscriptor** [TopShelfCraft/Wordsmith#60]
Hello! Are there plans and a timeline for upgrading the plugin for Craft CMS 5 compatibility?

Reference: https://craftcms.com/docs/5.x/extend/updating-plugins.html

**Comment by TUSAB-web** [comment]
I wanted to ask the same question as above. If the answer is no, that would be fine. But I’d love to know ASAP since I will have to re-code some templates if this isn’t going to become Craft 5 compatible.

**Comment by CreateSean** [comment]
Any word on this?

**Comment by michaelrog** [comment]
It's on the docket! I'll post here when it's out!

(If anybody needs it on a specific timeline, sponsorship and PRs are most welcome!)

**Comment by TUSAB-web** [comment]
Any chance that the above pull request would solve the issue?

**Comment by michaelrog** [comment]
Wordsmith `5.0.0` is out now with Craft 5 support! 🎉 

Thanks everybody for your patience!

**Comment by TUSAB-web** [comment]
Thank you!
