### ISSUE TITLE
Remove Markdown parsing

### ISSUE THREAD

**Issue by michaelrog** [TopShelfCraft/Wordsmith#61]
- Currently, the `markdown` and `md` filters are deprecated, because Craft provides them natively, and we don't want Wordsmith to conflict. (#57)
- Parsedown Extra is also antiquated; we need to ditch it. (#59)

Given that Craft's native [markdown filter](https://craftcms.com/docs/5.x/reference/twig/filters.html#markdown-or-md) supports more flavors, I think it's safe to remove Markdown parsing from Wordsmith altogether.

However, I like that Wordsmith, string methods are exposed as both Twig functions _and_ Twig filters. So maybe we can keep the `md()` function in place (but have it pass through to Craft's parser), and let Craft own the `|md` filter.

**Comment by iraritchiemeek** [comment]
@michaelrog You may want to update the docs to mention that this has been removed. I just spent a while trying to figure out why `pde` wasn't working.
